networks:
  laravel:

services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/services/php/Dockerfile
    container_name: ${DOCKER_SERVICES_NAME}_php
    restart: unless-stopped
    tty: true
    environment:
      DOCKER_SERVICES_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/services/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: ${DOCKER_SERVICES_NAME}_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_SERVICES_URL_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/services/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      - app


  #MySQL Service
  db:
    container_name: ${DOCKER_SERVICES_NAME}_db
    image: mysql/mysql-server:8.0.23
    restart: unless-stopped
    ports:
      - "${DOCKER_SERVICES_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      DOCKER_SERVICES_NAME: mysql
    volumes:
      - ./docker/services/mysql/data:/var/lib/mysql/
      - ./docker/services/mysql/conf/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
